# Generated by Django 4.2 on 2023-04-21 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0011_rename_indexes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='tiempo',
            new_name='cooking_time',
        ),
    ]
