# Generated by Django 4.2 on 2023-04-22 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0013_rename_izmerenie_ingredient_measurement_unit_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_favorite',
        ),
        migrations.RemoveConstraint(
            model_name='quantity_ingredientes',
            name='unique_combination',
        ),
        migrations.RenameField(
            model_name='quantity_ingredientes',
            old_name='receipt',
            new_name='recepi',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='for_shop',
            name='receipt',
        ),
        migrations.AddField(
            model_name='favorite',
            name='recepi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recepi', to='receipt.receipt', verbose_name='Любимый рецепт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='for_shop',
            name='recepi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_recepi', to='receipt.receipt', verbose_name='В список покупок'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recepi'), name='unique_favorite'),
        ),
        migrations.AddConstraint(
            model_name='quantity_ingredientes',
            constraint=models.UniqueConstraint(fields=('recepi', 'ingredient'), name='unique_combination'),
        ),
    ]
