# Generated by Django 4.2 on 2023-04-22 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipt', '0015_remove_favorite_unique_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='author',
            field=models.ForeignKey(help_text='Укажите автора', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='ingredients',
            field=models.ManyToManyField(help_text='Выберите ингридиенты', related_name='recipes', to='receipt.ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='tags',
            field=models.ManyToManyField(help_text='Выберите теги', related_name='recipes', to='receipt.tag', verbose_name='Теги'),
        ),
    ]
