# Generated by Django 4.2 on 2023-04-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0016_alter_receipt_author_alter_receipt_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
