# Generated by Django 4.2 on 2023-04-15 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipt', '0009_alter_for_shop_recept_alter_for_shop_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recept',
            new_name='Receipt',
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_favorite',
        ),
        migrations.RemoveConstraint(
            model_name='quantity_ingredientes',
            name='unique_combination',
        ),
        migrations.RenameField(
            model_name='quantity_ingredientes',
            old_name='recept',
            new_name='receipt',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='recept',
        ),
        migrations.RemoveField(
            model_name='for_shop',
            name='recept',
        ),
        migrations.AddField(
            model_name='favorite',
            name='receipt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_receipt', to='receipt.receipt', verbose_name='Любимый рецепт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='for_shop',
            name='receipt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_receipt', to='receipt.receipt', verbose_name='В список покупок'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'receipt'), name='unique_favorite'),
        ),
        migrations.AddConstraint(
            model_name='quantity_ingredientes',
            constraint=models.UniqueConstraint(fields=('receipt', 'ingredient'), name='unique_combination'),
        ),
    ]
