# Generated by Django 4.2 on 2023-04-12 21:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование ингридиента')),
                ('izmerenie', models.CharField(max_length=15, verbose_name='Единица измерения')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('color', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^#([a-fA-F0-9]{6})', message='Укажите цвет в формате HEX-кода.')], verbose_name='Цвет в HEX')),
                ('slug', models.SlugField(help_text='Уникальный адрес', max_length=25, unique=True, verbose_name='Адрес для ссылки')),
            ],
        ),
        migrations.CreateModel(
            name='Recept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Укажите название блюда', max_length=150, verbose_name='Название рецепта')),
                ('image', models.ImageField(help_text='Загрузите картинку ', upload_to='posts/', verbose_name='Изображение')),
                ('text', models.TextField(help_text='Здесь будет Ваш рецепт', verbose_name='Рецепт')),
                ('tiempo', models.DecimalField(decimal_places=0, help_text='Укажите время приготовления в минутах', max_digits=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(help_text='Укажите автора', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта')),
                ('ingridientes', models.ManyToManyField(help_text='Выберите ингридиенты', to='foodgram.ingredient', verbose_name='Ингридиенты')),
                ('tags', models.ManyToManyField(help_text='Выберите теги', to='foodgram.tag', verbose_name='Теги')),
            ],
        ),
        migrations.CreateModel(
            name='Quantity_ingredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodgram.ingredient', verbose_name='Ингредиент')),
                ('recept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodgram.recept', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Количество ингрилиентов для приготовления',
            },
        ),
        migrations.CreateModel(
            name='For_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodgram.recept', verbose_name='В список покупок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Список покупок',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodgram.recept', verbose_name='Любимый рецепт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Любимый автор')),
            ],
            options={
                'verbose_name': 'Избранное',
            },
        ),
    ]
