# Generated by Django 4.2 on 2023-04-12 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранные'},
        ),
        migrations.AlterModelOptions(
            name='quantity_ingredientes',
            options={'verbose_name': 'Количество ингредиентов для приготовления'},
        ),
    ]
