# Generated by Django 4.2 on 2023-04-12 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0003_alter_favorite_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='for_shop',
            options={'verbose_name': 'Список покупок', 'verbose_name_plural': 'Списки покупок'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='quantity_ingredientes',
            options={'verbose_name': 'Количество ингредиентов для приготовления', 'verbose_name_plural': 'Количество ингредиентов для приготовления'},
        ),
        migrations.AlterModelOptions(
            name='recept',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
